# Generated by Django 5.0.1 on 2024-02-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact_us_delete_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aboutus',
            new_name='home',
        ),
    ]
